CREATE TABLE TIB_PLUGIN
   (
       PLG_CODIGO NUMBER(18) NOT NULL,
       PLG_IDENTI VARCHAR2(255) NOT NULL,
       PLG_DESCR VARCHAR2(255) NOT NULL,
       PLG_CLASS VARCHAR2(500),
       PLG_PREFIJO VARCHAR2(500) NOT NULL,
       PLG_IDIPER VARCHAR2(500) NULL,
       PLG_IDIFRO VARCHAR2(500) NULL,
       PLG_PROPS VARCHAR2(4000),
       PLG_PORDEF NUMBER(1) DEFAULT 0 NOT NULL ,
       CONSTRAINT PK_TIB_PLUGIN PRIMARY KEY (PLG_CODIGO),
       CONSTRAINT UNIQUE_IDENTI UNIQUE (PLG_IDENTI)
   );
COMMENT ON COLUMN TIB_PLUGIN.PLG_CODIGO IS 'Código único de registro';
COMMENT ON COLUMN TIB_PLUGIN.PLG_IDENTI IS 'Identificador del plugin';
COMMENT ON COLUMN TIB_PLUGIN.PLG_DESCR IS 'Descripción del plugin';
COMMENT ON COLUMN TIB_PLUGIN.PLG_CLASS IS 'Clase asociada al plugin';
COMMENT ON COLUMN TIB_PLUGIN.PLG_PREFIJO IS 'Prefijo utilizado por el plugin';
COMMENT ON COLUMN TIB_PLUGIN.PLG_PROPS IS 'Propiedades adicionales del plugin';
COMMENT ON COLUMN TIB_PLUGIN.PLG_IDIPER IS 'Idiomas permitidos en el plugin';
COMMENT ON COLUMN TIB_PLUGIN.PLG_IDIFRO IS 'Idiomas permitidos en el frontal';
COMMENT ON COLUMN TIB_PLUGIN.PLG_PORDEF IS 'Indicador si el plugin es por defecto (0: No, 1: Sí)';
CREATE SEQUENCE TIB_PLUGIN_SEQ;


CREATE TABLE "TIB_CNFGLO"
(
    "CFG_CODIGO" NUMBER(10) NOT NULL,         -- Código
    "CFG_PROP"   VARCHAR2(100 CHAR) NOT NULL, -- Propiedad
    "CFG_VALOR"  VARCHAR2(500 CHAR) NULL,     -- Valor
    "CFG_DESCR"  VARCHAR2(255 CHAR) NOT NULL, -- Descripción propiedad
    "CFG_NOMOD"  NUMBER(1) DEFAULT 0 NOT NULL, -- No modificable
    CONSTRAINT PK_TIB_CNFGLO PRIMARY KEY (CFG_CODIGO)
);
CREATE SEQUENCE TIB_CNFGLO_SEQ;
COMMENT ON TABLE "TIB_CNFGLO" IS 'Propiedades configuración global';
COMMENT ON COLUMN "TIB_CNFGLO"."CFG_CODIGO" IS 'Código';
COMMENT ON COLUMN "TIB_CNFGLO"."CFG_PROP" IS 'Propiedad';
COMMENT ON COLUMN "TIB_CNFGLO"."CFG_VALOR" IS 'Valor';
COMMENT ON COLUMN "TIB_CNFGLO"."CFG_DESCR" IS 'Descripción propiedad';
COMMENT ON COLUMN "TIB_CNFGLO"."CFG_NOMOD" IS 'No modificable';


CREATE TABLE "TIB_CNFFRO"
(
    "CFF_CODIGO" NUMBER(10) NOT NULL,         -- Código
    "CFF_PLUGIN" NUMBER(10) NULL,             -- Plugin
    "CFF_IDIORI"  VARCHAR2(20 CHAR) NULL,     -- Idioma origen
    "CFF_IDIDES"  VARCHAR2(20 CHAR) NULL,     -- Idioma destino
    "CFF_PLGSOP"  VARCHAR2(1000 CHAR) NULL,   -- Plugins sorportados
    CONSTRAINT PK_TIB_CNFFRO PRIMARY KEY (CFF_CODIGO),
    CONSTRAINT FK_TIB_CNFFRO_PLUGIN FOREIGN KEY (CFF_PLUGIN)
        REFERENCES TIB_PLUGIN (PLG_CODIGO)        -- Clave foránea

);
CREATE SEQUENCE TIB_CNFFRO_SEQ;
COMMENT ON TABLE "TIB_CNFFRO" IS 'Propiedades configuración frontal';
COMMENT ON COLUMN "TIB_CNFFRO"."CFF_CODIGO" IS 'Código';
COMMENT ON COLUMN "TIB_CNFFRO"."CFF_PLUGIN" IS 'Plugin';
COMMENT ON COLUMN "TIB_CNFFRO"."CFF_IDIORI" IS 'Idioma origen';
COMMENT ON COLUMN "TIB_CNFFRO"."CFF_IDIDES" IS 'Idioma destino';
COMMENT ON COLUMN "TIB_CNFFRO"."CFF_PLGSOP" IS 'Plugins soportados';



CREATE TABLE "TIB_PROCES"
(
    "PROCES_CODIGO" NUMBER(10) NOT NULL,    -- Código
    "PROCES_CODENTI" NUMBER(10) NOT NULL,   -- Código Entidad
    "PROCES_IDENTI" VARCHAR2(10 CHAR) NOT NULL,    -- Identificador Proceso
    "PROCES_DESCRI" VARCHAR2(100 CHAR) NOT NULL,    -- Descripción
    "PROCES_CRON" VARCHAR2(100 CHAR) NULL,    -- Cron
    "PROCES_ACTIVO" NUMBER(1) NOT NULL,    -- Activo
    "PROCES_PARAMS" VARCHAR2(2000 CHAR) NULL,    -- Parámetros Invocación
    CONSTRAINT PK_TIB_PROCES PRIMARY KEY (PROCES_CODIGO)
);
CREATE SEQUENCE  "RS2_PROCES_SEQ" ;

COMMENT ON COLUMN TIB_PROCES.PROCES_CODIGO IS 'CODIGO';
COMMENT ON COLUMN TIB_PROCES.PROCES_IDENTI IS 'IDENTIFICADOR PROCESO';
COMMENT ON COLUMN TIB_PROCES.PROCES_CODENTI IS 'ENTIDAD';
COMMENT ON COLUMN TIB_PROCES.PROCES_DESCRI IS 'DESCRIPCION PROCESO';
COMMENT ON COLUMN TIB_PROCES.PROCES_CRON IS 'CRON';
COMMENT ON COLUMN TIB_PROCES.PROCES_ACTIVO IS 'ACTIVO';
COMMENT ON COLUMN TIB_PROCES.PROCES_PARAMS IS 'PARAMETROS INVOCACION (SERIALIZADO JSON)';
