DROP SEQUENCE TIB_PLUGIN_SEQ;
DROP SEQUENCE TIB_CNFGLO_SEQ;
DROP SEQUENCE TIB_CNFFRO_SEQ;
DROP SEQUENCE  "TIB_PROCES_SEQ" ;

DROP TABLE TIB_CNFGLO;
DROP TABLE TIB_CNFFRO;
DROP TABLE TIB_PLUGIN;
DROP TABLE TIB_PROCES;

